# skaffold.yaml
---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: openapi-tools

requires:
  - configs: ["openapi-merger"]
    path: services/openapi-merger
    activeProfiles: &profiles
      - name: local
        activatedBy: [local]
      - name: development
        activatedBy: [development]
      - name: staging
        activatedBy: [staging]
      - name: production
        activatedBy: [production]