# openapi-merger/skaffold.yaml
---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: openapi-merger

profiles:
  - name: local
    build: &build
      tagPolicy:
        sha256: {}
      artifacts:
        - image: openapi-merger
          context: .
          docker:
            dockerfile: docker/Dockerfile.native
            target: production
      local:
        useBuildkit: true
        concurrency: 0
    deploy: &deploy
      kubeContext: minikube
      kubectl: {}
    manifests: &manifests
      kustomize:
        paths:
          - ./k8s/overlays/development
    portForward: &portForward
      - resourceType: service
        resourceName: openapi-merger
        namespace: fw-api
        port: 8080
        localPort: 8090

  - name: development
    build: *build
    deploy: *deploy
    manifests: *manifests
    portForward: *portForward

  - name: staging
    deploy: *deploy
    manifests:
      kustomize:
        paths:
          - ./k8s/overlays/staging
    portForward: *portForward

  - name: production
    deploy: *deploy
    manifests:
      kustomize:
        paths:
          - ./k8s/overlays/production
    portForward: *portForward
