####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/openapi-merger .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/openapi-merger
#
# The ` registry.access.redhat.com/ubi8/ubi-minimal:8.10` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/ubi8/ubi-minimal:8.10`.
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10 AS build

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

# Stage 2 : Create the docker final image for production
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10 AS production

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# Set up non-root user
# USER 185

WORKDIR /app

# Copy the binary to the production image from the builder stage
COPY --chown=1001:root --chmod=0755 --from=build /work/target/*-runner /app/openapi-merger

EXPOSE 8080
USER 1001

ENTRYPOINT ["./openapi-merger", "-Dquarkus.http.host=0.0.0.0"]
