# Base configuration
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H

# Swagger UI config
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Native build config
quarkus.native.additional-build-args=--initialize-at-run-time=io.swagger.v3.core.util.Json

# Memory and thread configuration
quarkus.thread-pool.core-threads=1
quarkus.thread-pool.max-threads=20
quarkus.vertx.worker-pool-size=20

# Log configuration
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.mycompany.openapi".level=DEBUG

# GitHub authentication config
github.token=${GITHUB_TOKEN:empty}