name: OpenAPI Merger CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
    SOURCE_DIR: ./services/openapi-merger
    OPENAPI_MERGER_VERSION: 2.9 # see Dockerfile
    JAVA_VERSION: 17 # see Dockerfile
    JAVA_DISTRIBUTION: temurin # see Dockerfile
    DOCKER_REGISTRY: ${{ vars.DOCKERHUB_REGISTRY }}
    DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    DOCKER_IMAGE_NAME: ${{ vars.DOCKERHUB_REPOSITORY }}/openapi-merger
    DOCKER_BAKE_FILE: docker-bake.hcl
    DOCKER_BAKE_TARGET: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
    
    - name: Run Tests
      run: ./mvnw test
    
    - name: Build and Push Docker Image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/openapi-merger:latest
          ghcr.io/${{ github.repository }}/openapi-merger:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Deploy to Kubernetes
    #   if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    #   uses: steebchen/kubectl@v2
    #   with:
    #     config: ${{ secrets.KUBE_CONFIG_DATA }}
    #     command: |
    #       set -e
    #       # Update kubernetes/deployment.yaml with the new image tag
    #       sed -i "s|\${DOCKER_REGISTRY}|ghcr.io/${{ github.repository }}|g" kubernetes/deployment.yaml
    #       sed -i "s|\${VERSION}|${{ github.sha }}|g" kubernetes/deployment.yaml
    #       sed -i "s|\${GITHUB_TOKEN_BASE64}|${{ secrets.GITHUB_TOKEN_BASE64 }}|g" kubernetes/deployment.yaml
    #       # Apply the updated deployment
    #       kubectl apply -f kubernetes/deployment.yaml